apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wind-turbine
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/tyamakawrh/quinoa-wind-turbine-manifests
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
